# Generated by Django 4.0.1 on 2022-01-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_suggestionadmn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='suggestionAdmn',
            new_name='Message',
        ),
    ]
